### ISSUE TITLE
It would be great if the package could be compiled by the catkin_make_isolated

### ISSUE THREAD

**Issue by kubelvla** [norlab-ulaval/norlab_icp_mapper#1]
In the dedicated branch, I've created the package.xml and naively expected it to work. But the depending norlab_icp_mapper_ros misses the header file for compilation. So I've looked into libnabo and libpointmatcher CMakeLists.txt and realized that there is more stuff to do which I don't understand. So, Simon Pierre, :D, I would like to ask you for a little help there pleeease 

There is already a new branch for that with the xml file I created

**Comment by kubelvla** [comment]
The problem is this:
The cmake sets my include directories as this:
-----------------INCLUDE DIRS-----------------------
/home/student/percep3d_workspace/external_libraries/devel_isolated/libpointmatcher/include /usr/include
/usr/include/eigen3
/home/student/percep3d_workspace/external_libraries/devel_isolated/libnabo/include
/home/student/percep3d_workspace/external_libraries/devel_isolated/norlab_icp_mapper/include/norlab_icp_mapper
-------------INCLUDE DIRS END---------------------------

But the source header file looks for "norlab_icp_mapper/Mapper.h", the folder name is repeated...
Then I get this error:

**/home/student/percep3d_workspace/catkin_workspace/src/norlab_icp_mapper_ros/src/NodeParameters.h:2:10: fatal error: norlab_icp_mapper/Mapper.h: No such file or directory
 #include "norlab_icp_mapper/Mapper.h"**


There is something with the path, the included path by cmake should not contain "norlab_icp_mapper". For now, I am hotfixing the problem by just including "Mapper.h"

**Comment by peci1** [comment]
#2

**Comment by kubelvla** [comment]
At least the darpa branch does this correctly now
