### ISSUE TITLE
Regarding documentation of ICP mapper

### ISSUE THREAD

**Issue by miso037** [norlab-ulaval/norlab_icp_mapper#12]
Hello,

currently i am using ICP mapper in my bachelor thesis. I was not able to find any article regarding this particular ICP mapper, or any other documentation that would explain inner workings of ICP mapper. I understand how registration and localization part works and i find the review "A Review of Point Cloud Registration Algorithms for Mobile Robotics" by François Pomerleau, Francis Colas, Roland Siegwart is sufficient to explain the principle combined with libpointmatcher documentation. However, im using SLAM configuration with computing of probability of points being dynamic. What method of determining the probability of points being dynamic is used by ICP mapper ? Also, are there some articles specifically writen about this mapper ?

Thanks in advance for your reply. If i missed some obviously linked documentation, i want to apologise beforehand.

**Comment by simonpierredeschenes** [comment]
Hi,  thank you for your interest in our mapper! There is no documentation for the mapping library for now,  but there is some documentation about our ROS wrapper: https://github.com/norlab-ulaval/Norlab_wiki/wiki/Tutorials:-3D-Mapping. You can also take a look at the code of the ROS wrapper to see a usage example of the library: https://github.com/norlab-ulaval/norlab_icp_mapper_ros. There is this article which explains a bit the inner workings of the mapper among our teach and repeat framework: https://arxiv.org/abs/2111.13981. Finally, there is this article which describes how the dynamic point filtering algorithm works: https://ieeexplore.ieee.org/abstract/document/6907397. I hope this will be useful!

**Comment by miso037** [comment]
Hello,

i just wanted to thank you for your reply. I have done some succesfull autonomous rides based on this SLAM, and your sources helped me to understand inner workings of Mapper more. I might add one more suggestion, although you probablty thought about it already. I was using heavily downsampled input point cloud from lidar. I have noticed that dynamic points computation is based on filtered input point cloud. I was able to improve dynamic point removal by inputing not filtered point cloud into dynamic points computation. It would be nice having an option to use none, or only some input point cloud filters for dynamic points computation and then use rest of the filters for ICP. Anyways, i had fun working with this package, so thank you for making it open-source. I will not need any more information for now. You can close this thread, if you want to.
