### ISSUE TITLE
Update libpointmatcher required version

### ISSUE THREAD

**Issue by fdila** [norlab-ulaval/norlab_icp_mapper#18]
Hi!
I've noticed that the libpointmatcher version specified in the CMakeLists does not match the actual requirements of norlab_icp_mapper.
Actually, there is no "official" libpointmatcher version that is compatible with this repo, I switched to the "develop" branch of libpointmatcher to make icp_mapper compile.
It would be nice to specify it in the readme, or release a new version of libpointmatcher and update the CMake requirements.

**Comment by boxanm** [comment]
Hi @fdila. thanks for noticing this issue! It is something we missed when stabilizing the mapper. I'll make a new libpointmatcher release reflecting the changes soon and will ping you here once it's done.

**Comment by boxanm** [comment]
Hi @fdila , a new libpointmatcher version 1.4.3 was [released](https://github.com/norlab-ulaval/libpointmatcher/releases/tag/1.4.3), you can now use the mapper with this tag.
