### ISSUE TITLE
Infinite_corridor branch

### ISSUE THREAD

**Issue by Cristian-wp** [norlab-ulaval/norlab_icp_mapper#7]
Hello, what is the purpose of this branch?By the name, I can assume that the icp does not get lost in a "infinite corridor" really poor of feature.
This is correct or maybe the meaning is another?

**Comment by simonpierredeschenes** [comment]
Hi @Cristian-wp , thank you for your interest in our mapper! No, unfortunately, this is not what the branch does, maybe it should be renamed. What this branch does (it is still highly experimental) is that it creates an odometric map, which is homotopic to an infinite corridor. What I mean by that is that if a big loop is performed while mapping, the part of the map at the start of the loop will not be reused when the platform closes the loop. Instead, the mapper will continue to expand the map, as if this part of the world had never been explored. I hope this clarify things for you.

**Comment by Cristian-wp** [comment]
Yes, thanks a lot

**Comment by Cristian-wp** [comment]
@simonpierredeschenes can you please look at my other issue?  This is regarding the ROS intergrator (I have use the the norlab_icp_mapper master branch)
